name: Auto Commit README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch: # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Prevents credential issues

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update README.md
        run: |
          echo "Last updated: $(date -u)" > README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README.md [skip ci]" || exit 0
          git pull --rebase
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/automation-commit.git main
